export const privacyPolicy = {
  title: "Privacy Policy for Xapi Platform",
  sections: [
    {
      title: "1. Information Collection",
      content: [
        "1.1.\nWhat Information We Collect",
        "We may collect the following types of information:",
        `- **Contact Information:** A user is required to provide basic contact information, e.g., name and email address to create an account for the Services and identify you when you sign in to your account.`,
        `- **Account information:** To administer, manage, or update an Xapi account, you or a Customer (the entity purchasing the Services if not an individual) supply Xapi with names and email addresses for authorized users of the account, a domain and/or similar account details with respect to its users. In addition, self-service Customers that purchase a paid version of the Services provide Xapi (or its payment processors) with billing details such as credit card information, and/or a billing address.`,
        `- **Usage Data:** Information about your interactions with the Services.`,
        `- **Log Data:** Information automatically collected when you interact with our Site and Services by our servers, including but not limited to IP address and browser type.`,
        `- **Cookies and Similar Technologies:** Please refer to ‘Cookies and Similar Technologies’ under the below section.`,
        "1.2.\nHow We Collect Information",
        `- We collect information through:`,
        `- Information provided by you during account creation and usage.`,
        `- Automated collection through cookies and similar technologies.`,
        `- Data generated by your usage of our platform.`,
      ],
    },
    {
      title: "2. How We Use Information",
      content: [
        "Xapi use the collected information to:",
        "- Provide, maintain, and improve our services.",
        "- Communicate with you and respond to your inquiries.",
        "- Customize your experience and preferences.",
        "- Analyze usage patterns and trends.",
        "- Prevent misuse, fraud, and security breaches.",
      ],
    },
    {
      title: "3. Information Sharing and Disclosure",
      content: [
        "Xapi do not share your personal information with third parties except as described in this policy or with your consent.",
      ],
    },
    {
      title: "4. Cookies and Similar Technologies",
      content: [
        "Cookies are small data files stored on your browser by our Site and Services. We use cookies and similar technologies for improving user experience and analytics.",
        "4.1.\nThird Party Cookies",
        "We may use third-party cookies for analytics, advertising, and other purposes. You can manage your cookie preferences through your browser settings.",
        "4.2.\nGoogle Analytics",
        "We use Google Analytics, a web analytics service provided by Google, Inc., on our Site. Google Analytics uses cookies or other tracking technologies to help us analyze how users interact with and use the Site, compile reports on the Site’s activity, and provide other services related to Site activity and usage. The technologies used by Google may collect information such as your IP address, time of visit, whether you are a return visitor, and any referring website. The Site does not use Google Analytics to gather information that personally identifies you. The information generated by Google Analytics will be transmitted to and stored by Google and will be subject to Google’s privacy policies.",
      ],
    },
    {
      title: "5. Your Choices",
      content: [
        "5.1.\nAccess, Correction, and Deletion",
        "You may access, correct, or delete your personal information by contacting us through the provided contact information.",
        "5.2.\nOpt-Out",
        "You can opt-out of certain communications and notifications. Please refer to the opt-out instructions in our communications.",
      ],
    },
    {
      title: "6. Security",
      content: [
        "We employ industry-standard security measures to protect your personal information from unauthorized access, use, or disclosure.",
      ],
    },
    {
      title: "7. Data Retention",
      content: [
        "We retain your information for as long as needed to provide our services and as required by applicable laws. We will securely delete your information once it is no longer needed.",
      ],
    },
    {
      title: "8. Changes to this Policy",
      content: [
        "We may update this Privacy Policy to reflect changes in our practices and services. The updated policy will be effective upon posting on our website.",
      ],
    },
    {
      title: "9. Contact Us",
      content: [
        "For any questions, concerns, or inquiries about this Privacy Policy, please contact us at **info@x-venture.io**.",
      ],
    },
  ],
};
